# Generated by Django 5.1.3 on 2025-06-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_payment_order_remove_payment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_requested',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processed', 'Processed')], default='none', max_length=20, null=True),
        ),
    ]
