# Generated by Django 5.1.3 on 2025-06-22 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_created_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_pending_order_user',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_pending_order_session',
        ),
    ]
