# Generated by Django 5.1.3 on 2025-06-22 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_unique_pending_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_pending_order_user',
        ),
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_pending_order_session',
        ),
    ]
