# Generated by Django 5.1.3 on 2025-06-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='Description')),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Discount')),
                ('is_subscription', models.BooleanField(blank=True, default=False, null=True)),
                ('delivery_frequency', models.CharField(blank=True, choices=[('none', 'One-time Purchase'), ('daily', 'Daily Delivery'), ('monthly', 'Monthly Delivery')], default='none', help_text='Optional delivery frequency if product is a subscription', max_length=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('sold', models.PositiveIntegerField(default=0)),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('image', models.ImageField(default='products/coffee-packed-white-coffee-.jpg', upload_to='products/', verbose_name='Image')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Updated_at')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('subscription', 'Subscription'), ('seasonal', 'Seasonal'), ('promo', 'Promo Code')], max_length=20)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=50, null=True)),
                ('applies_to_subscriptions', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('return', 'Return')], max_length=10)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
