# Generated by Django 5.1.3 on 2025-06-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='', max_length=50, verbose_name='Quantity'),
            preserve_default=False,
        ),
    ]
