# Generated by Django 5.1.3 on 2025-06-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(default='50kg', max_length=50, verbose_name='Quantity'),
        ),
    ]
