# Generated by Django 5.1.3 on 2025-06-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='applies_to_subscriptions',
            field=models.BooleanField(default=False),
        ),
    ]
