# Generated by Django 5.1.3 on 2025-06-03 07:38

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(to='blog.category', verbose_name='Categories'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ForeignKey(blank=blog.models.Tag, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.tag', verbose_name='Tag'),
        ),
    ]
