# Generated by Django 5.1.3 on 2025-06-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='coments',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
