# Generated by Django 5.1.3 on 2025-06-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_coments_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
