# Generated by Django 5.1.3 on 2025-06-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_comments_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='guest_session_id',
        ),
    ]
