# Generated by Django 5.1.3 on 2025-06-25 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_reactions_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', unique=True, verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='reaction',
            field=models.CharField(blank=True, choices=[('Like', 'like'), ('disLike', 'dislike'), ('Love', 'love'), ('Sad', 'sad'), ('Funny', 'funny')], max_length=50, null=True, verbose_name='Reactions'),
        ),
    ]
