# Generated by Django 5.1.3 on 2025-06-25 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_reactions_blog_alter_reactions_reaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='Blog'),
        ),
        migrations.AlterField(
            model_name='reactions',
            name='reaction',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike'), ('love', 'Love'), ('sad', 'Sad'), ('funny', 'Funny')], max_length=50, null=True, verbose_name='Reactions'),
        ),
        migrations.AlterUniqueTogether(
            name='reactions',
            unique_together={('author', 'blog')},
        ),
    ]
