# Generated by Django 5.1.3 on 2025-06-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_reactions_blog_alter_reactions_reaction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactions',
            old_name='reaction',
            new_name='type',
        ),
    ]
