# Generated by Django 5.1.3 on 2025-06-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_rename_reaction_reactions_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactions',
            old_name='type',
            new_name='reaction',
        ),
    ]
