# Generated by Django 5.1.3 on 2025-06-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_type_reactions_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reactions',
            name='reaction',
            field=models.CharField(blank=True, choices=[('like', 'Like'), ('dislike', 'Dislike'), ('love', 'Love'), ('sad', 'Sad'), ('funny', 'Funny'), ('angry', 'Angry')], max_length=50, null=True, verbose_name='Reactions'),
        ),
    ]
