name: Deploy Django + React

on:
  push:
    branches:
      - main  # or your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3



    # Python build
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    # Deploy to VPS
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        port: 22
        script: |
          cd /var/www/abrencoffee
          git pull origin main
          
          # Activate venv
          source venv/bin/activate
          
          # Install Python deps
          pip install -r requirements.txt
          
          # Collect static and migrate
          python manage.py collectstatic --noinput
          python manage.py migrate
          
          # Restart Gunicorn
          sudo supervisorctl restart abrencoffee
